SignUp, SignIn, ChangePassword
creating-and-editing-a-resume/backend pull request #8
Opened 2023-11-17 11:45 UTC by Itdxl

2023-11-17 12:23 UTC, EvgVol reviewed
https://docs.google.com/spreadsheets/d/1_yZZNUAzC8N1EmjLFrpKMsnw4SmdO5qjc9hpAAZgZ90/edit#gid=0

2023-11-17 12:23 UTC, EvgVol commented on .gitignore
> +creating_and_editing_a_resume/user/migrations/
https://git-scm.com/docs/gitignore#_pattern_format

2023-11-17 12:23 UTC, EvgVol commented on creating_and_editing_a_resume/creating_and_editing_a_resume/settings.py
> +}
нет пустой строки

2023-11-17 12:23 UTC, EvgVol commented on creating_and_editing_a_resume/creating_and_editing_a_resume/urls.py
> +    path("api/v1/signup/", djoser_views.UserViewSet.as_view({'post': 'create'}), name='create-user'),
строка с 7 по 9  - так не пойдет. чтобы зарегистрироваться пользователь должен вводить api/v1/signup/ и т.д.

2023-11-17 12:23 UTC, EvgVol commented on creating_and_editing_a_resume/user/models/user.py
>  class ResumeUser(AbstractUser):
надо править модель resumeUser на основании данных которые нам дал ПМ

2023-11-17 12:23 UTC, EvgVol commented on creating_and_editing_a_resume/user/urls.py
> +]
пустая строка?

2023-11-17 12:23 UTC, EvgVol commented on requirements.txt
а зачем? мы же применяем poetry

2023-11-17 12:23 UTC, EvgVol commented on tashOBOBOAOA
тут зачем этот файил?

2023-11-17 16:54 UTC, dmitrii-r requested changes
Надо установить и настроить poetry. Запустить pre-commits. Тогда все зависимости установятся и прекоммит приведет код к PEP8

2023-11-23 04:49 UTC, EvgVol reviewed
https://docs.google.com/spreadsheets/d/1_yZZNUAzC8N1EmjLFrpKMsnw4SmdO5qjc9hpAAZgZ90/edit#gid=0

2023-11-23 04:49 UTC, EvgVol commented on .gitignore
> +creating_and_editing_a_resume/user/migrations/*
https://git-scm.com/docs/gitignore
должна быть пустая строка.

2023-11-23 04:49 UTC, EvgVol commented on creating_and_editing_a_resume/creating_and_editing_a_resume/settings.py
> +
нужно прописать :
LOGIN_URL
LOGIN_REDIRECT_UR
LOGOUT_REDIRECT_URL

https://docs.djangoproject.com/en/4.2/ref/settings/#login-url

2023-11-23 04:49 UTC, EvgVol commented on creating_and_editing_a_resume/creating_and_editing_a_resume/urls.py
> +    path("signup/", djoser_views.UserViewSet.as_view({'post': 'create'}), name='create-user'),
есть ли смысл импортировать из джосера views и потом присваивать имя как djoser_views, может сразу импортировать UserViewSet, TokenCreateView?

pep8. у тебя пре-коммит установлен?

2023-11-23 04:49 UTC, EvgVol commented on creating_and_editing_a_resume/creating_and_editing_a_resume/urls.py
> +    path('user/', include('user.urls')),
этот эндпоинт не предусмотрен.

2023-11-23 04:49 UTC, EvgVol commented on creating_and_editing_a_resume/user/models/user.py
>  class ResumeUser(AbstractUser):
нет first_name и last_name

2023-11-23 04:49 UTC, EvgVol commented on creating_and_editing_a_resume/user/views.py
> +class ChangePasswordView(APIView):
мы же используем djoser. не нужно создавать новую вьюху

2023-11-23 04:49 UTC, EvgVol commented on creating_and_editing_a_resume/user/urls.py
> +    path("change-password/", ChangePasswordView.as_view(), name='change-password'),
нужно импортировать UserViewSet и переопределять set-password.

2023-11-23 04:49 UTC, EvgVol commented on creating_and_editing_a_resume/user/models/user.py
> +                regex=r'^\d{2}\.\d{2}.\d{4}$',
Только цифры, точки.
Дни - 2 символа , **значения от 1 до 31 включительно.**
Месяцы - 2 символа, **значения от 1 до 12 включительно.**
Нули перед однозначным числом обязательны.
Длина 10 символов.

2023-11-23 04:49 UTC, EvgVol commented on creating_and_editing_a_resume/user/models/user.py
>          null=True,
https://docs.djangoproject.com/en/4.2/ref/models/fields/#null

2023-11-23 04:49 UTC, EvgVol commented on creating_and_editing_a_resume/user/models/user.py
>      city = models.CharField(
Только кириллица, пробел, тире.
Длина от 2 до 50 символов включительно.

2023-11-23 04:49 UTC, EvgVol commented on creating_and_editing_a_resume/user/models/user.py
> +                regex=r'^@[a-zA-Z0-9_]{5,32}$',
Формат: t.me/name

2023-11-23 04:49 UTC, EvgVol commented on creating_and_editing_a_resume/user/models/user.py
>  class ResumeUser(AbstractUser):
нет photo

2023-11-23 05:19 UTC, EvgVol commented on creating_and_editing_a_resume/user/models/user.py
> +                regex=r'^\d{2}\.\d{2}.\d{4}$',
Я предлагаю вернуть обратно DateField. где должна быть дата, пусть будет дата

2023-11-23 08:18 UTC, Itdxl commented on creating_and_editing_a_resume/creating_and_editing_a_resume/urls.py
> +    path('user/', include('user.urls')),
Да, как и смена пароля.

2023-11-23 08:19 UTC, Itdxl commented on creating_and_editing_a_resume/user/urls.py
> +    path("change-password/", ChangePasswordView.as_view(), name='change-password'),
Да, так можно сделать, что это изменит? + про смену пароля это предварительно, у нас этого вообще не запрашивали.

2023-11-23 08:38 UTC, EvgVol reviewed
ссылку на телеграм нужно чтобы сохранялась в формате t.me/name, а номер телефона был в формате +7(...)(...)(..)(..). 

Я считаю что писать регулярку и заставлять писать пользователя в нужном нам формате это не совсем корректно. достаточно будет сделать регулярке на корректный ввод номера телефона в формате +79876543210 и требований телеграмма по длине символов, а уже в методе def save(self, *args, **kwargs) задать нужное нам поведение сохранения переменных.

2023-11-23 08:38 UTC, EvgVol commented on creating_and_editing_a_resume/user/models/user.py
> +class CustomUserManager(BaseUserManager):
Нужно прописать метод создания супер пользователя. иначе будет вылетать исключение, т.к. мы переопределили стандартное поведение

2023-11-23 08:38 UTC, EvgVol commented on creating_and_editing_a_resume/user/urls.py
> +    path("change-password/", ChangePasswordView.as_view(), name='change-password'),
просто зачем заново создавать вьюху когда можно взять готовую из джосера

2023-11-23 08:38 UTC, EvgVol commented on creating_and_editing_a_resume/creating_and_editing_a_resume/urls.py
> +    path('user/', include('user.urls')),
можешь убрать смену пароля)

2023-11-23 08:38 UTC, EvgVol commented on creating_and_editing_a_resume/user/models/user.py
> +                regex=r'^\+\d{1,3}\s?\(\d{3}\)\s?\(\d{3}-\d{2}-\d{2}\)$',
проверь её, она не корректная

2023-11-23 08:38 UTC, EvgVol commented on creating_and_editing_a_resume/user/models/user.py
> +        validators=[
здесь это не нужно.
https://docs.djangoproject.com/en/4.2/ref/models/fields/#emailfield

2023-12-03 06:50 UTC, EvgVol commented on creating_and_editing_a_resume/creating_and_editing_a_resume/settings.py
> +LOGIN_URL = '/signin/'
норм но лучше сделать через reverse_lazy(), чтобы потом если измениться эндпоинт не словить ошибку

https://docs.djangoproject.com/en/4.2/ref/urlresolvers/#reverse-lazy

2023-12-03 06:50 UTC, EvgVol commented on creating_and_editing_a_resume/creating_and_editing_a_resume/settings.py
> +LOGIN_REDIRECT_URL = '/my-profile/'
https://docs.djangoproject.com/en/4.2/ref/urlresolvers/#reverse-lazy

2023-12-03 06:50 UTC, EvgVol commented on creating_and_editing_a_resume/user/models/user.py
> +    "Номер телефона",
pep 8

2023-12-03 06:50 UTC, EvgVol commented on creating_and_editing_a_resume/user/models/user.py
> +            regex=r'^\+7\d{10,12}$',
сейчас у тебя разрешено +79999999999, +79999999999**0**

2023-12-06 11:59 UTC, EvgVol approved these changes

2023-12-11 11:29 UTC, v-mcsimoff approved these changes
Кажется, что всё ок

2023-12-11 12:40 UTC, merged